# Generated by Django 6.0.7 on 2026-07-25 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rede', models.CharField(help_text='Ex: 100.64.0.0/10 (IPv4) ou 2001:db8::/32 (IPv6)', max_length=45)),
                ('tipo_uso', models.CharField(help_text='Ex: CGNAT, IPs Públicos Clientes, Loopback', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos_ip', to='gestao.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: OLT Huawei MA5800, CCR1036, Node Proxmox', max_length=100)),
                ('tipo', models.CharField(choices=[('R', 'Roteador/Borda'), ('O', 'OLT'), ('S', 'Switch'), ('V', 'Servidor/Virtualizador')], max_length=1)),
                ('ip_gerencia', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Gerência')),
                ('anotacoes', models.TextField(blank=True, help_text='Portas lógicas, credenciais padrão, detalhes físicos')),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='gestao.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.PositiveIntegerField(verbose_name='VLAN ID')),
                ('nome', models.CharField(help_text='Ex: PPPoE, Gerência OLT, Transporte L2', max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlans', to='gestao.cliente')),
                ('equipamento_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infraestrutura.equipamento')),
            ],
        ),
    ]
