# Generated by Django 6.0.7 on 2026-07-25 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
        ('infraestrutura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeradorVlanLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_inicial', models.PositiveIntegerField()),
                ('vlan_final', models.PositiveIntegerField()),
                ('nome_base', models.CharField(help_text='Ex: Clientes_PPPoE_Concentrador_1', max_length=100)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.cliente')),
                ('equipamento_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infraestrutura.equipamento')),
            ],
            options={
                'verbose_name': 'Gerador de VLANs em Lote',
                'verbose_name_plural': 'Gerar VLANs em Lote',
            },
        ),
    ]
