# Generated by Django 6.0.7 on 2026-07-28 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
        ('infraestrutura', '0002_geradorvlanlote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geradorvlanlote',
            options={'verbose_name': 'Gerar VLANs em Lote', 'verbose_name_plural': 'Gerar VLANs em Lote'},
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='anotacoes',
        ),
        migrations.RemoveField(
            model_name='geradorvlanlote',
            name='data_geracao',
        ),
        migrations.RemoveField(
            model_name='vlan',
            name='descricao',
        ),
        migrations.AddField(
            model_name='vlan',
            name='interface',
            field=models.CharField(blank=True, help_text='Ex: sfp-sfpplus1, gpon 0/1/2, bond0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.cliente'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ip_gerencia',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('R', 'Roteador/Borda'), ('S', 'Switch/Core'), ('O', 'OLT'), ('V', 'Servidor/Virtualização')], max_length=1),
        ),
        migrations.AlterField(
            model_name='geradorvlanlote',
            name='nome_base',
            field=models.CharField(help_text='Ex: VLAN-CLIENTES (Gerará VLAN-CLIENTES-100, etc)', max_length=100),
        ),
        migrations.AlterField(
            model_name='geradorvlanlote',
            name='vlan_final',
            field=models.IntegerField(help_text='Ex: 150'),
        ),
        migrations.AlterField(
            model_name='geradorvlanlote',
            name='vlan_inicial',
            field=models.IntegerField(help_text='Ex: 100'),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.cliente'),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='vlan_id',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Subrede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(help_text='Ex: 192.168.100.0/24 ou 2001:db8::/32', max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('interface', models.CharField(blank=True, help_text='Ex: ether2, vlan100', max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.cliente')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infraestrutura.equipamento')),
                ('rede_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subredes_filhas', to='infraestrutura.subrede')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infraestrutura.vlan')),
            ],
            options={
                'verbose_name': 'Subrede',
                'verbose_name_plural': 'Subredes',
                'unique_together': {('cliente', 'prefixo')},
            },
        ),
        migrations.CreateModel(
            name='EnderecoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.GenericIPAddressField(help_text='Endereço IP individual')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('R', 'Reservado'), ('D', 'Desativado')], default='A', max_length=1)),
                ('subrede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_ip', to='infraestrutura.subrede')),
            ],
            options={
                'verbose_name': 'Endereço IP',
                'verbose_name_plural': 'Endereços IP',
            },
        ),
        migrations.DeleteModel(
            name='BlocoIP',
        ),
    ]
