# Generated by Django 6.0.7 on 2026-07-25 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao', '0001_initial'),
        ('infraestrutura', '0002_geradorvlanlote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Resumo do problema ou solicitação', max_length=200)),
                ('descricao', models.TextField(help_text='Descrição detalhada do chamado')),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('E', 'Em Andamento'), ('C', 'Concluído'), ('X', 'Cancelado')], default='A', max_length=1)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='gestao.cliente')),
                ('equipamento', models.ForeignKey(blank=True, help_text='Opcional: Equipamento relacionado ao problema', null=True, on_delete=django.db.models.deletion.SET_NULL, to='infraestrutura.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Apontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('descricao_atividade', models.TextField(help_text='O que foi feito nesta intervenção?')),
                ('tempo_gasto', models.DecimalField(decimal_places=2, help_text='Tempo gasto em horas (Ex: 1.5 para 1h30min, 0.5 para 30min)', max_digits=5)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='helpdesk.ticket')),
            ],
        ),
    ]
