# Generated by Django 6.0.7 on 2026-07-25 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
        ('infraestrutura', '0002_geradorvlanlote'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hora_inicio_cronometro',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tempo_acumulado_segundos',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='apontamento',
            name='tempo_gasto',
            field=models.DecimalField(decimal_places=2, help_text='Tempo em horas (Ex: 1.5 para 1h30min)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infraestrutura.equipamento'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('E', 'Em Andamento'), ('G', 'Aguardando Cliente'), ('C', 'Concluído'), ('X', 'Cancelado')], default='A', max_length=1),
        ),
    ]
