"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%96ond@yvg&$=sz3shrtqg^knw7l92ei645xhxyt674yw5hl5&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestao',
    'infraestrutura',
    'helpdesk',
    'portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# --- INTERNACIONALIZAÇÃO ---
LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Recife'

USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# --- CONFIGURAÇÕES DE LOGIN DO PORTAL ---
# Diz ao Django onde fica a nossa tela de login
LOGIN_URL = 'login' 

# Para onde enviar o cliente após ele fazer o login com sucesso (nossa Dashboard)
LOGIN_REDIRECT_URL = 'dashboard' 

# Para onde enviar o cliente após ele clicar em Sair
LOGOUT_REDIRECT_URL = 'login'

# ==========================================
# CONFIGURAÇÕES DO JAZZMIN (ADMIN MODERNO)
# ==========================================
JAZZMIN_SETTINGS = {
    "site_title": "Admin - Consultoria",
    "site_header": "Gestão ERP",
    "site_brand": "Painel de Controle",
    "welcome_sign": "Bem-vindo ao ERP de Consultoria",
    "copyright": "Gestão de Provedores e Redes",
    
# Ícones do menu lateral (Agora com as letras maiúsculas exatas dos modelos)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "gestao.Cliente": "fas fa-building",
        "gestao.Contrato": "fas fa-file-signature",
        "helpdesk.Ticket": "fas fa-ticket-alt",
        "infraestrutura.Equipamento": "fas fa-server",
        "infraestrutura.Vlan": "fas fa-network-wired",
        "infraestrutura.Subrede": "fas fa-project-diagram",
        "infraestrutura.EnderecoIP": "fas fa-ethernet",
        "infraestrutura.GeradorVlanLote": "fas fa-layer-group",
        "portal.PerfilCliente": "fas fa-id-badge",
        "custom_css": "css/admin_custom.css", # <-- ADICIONE ESTA LINHA AQUI
    },
    
    "show_ui_builder": False,
}

# --- CONFIGURAÇÕES VISUAIS ESTILO NETBOX ---
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False, 
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    
    # --- AS DUAS LINHAS ABAIXO CORRIGEM O DESLOCAMENTO ---
    "sidebar_nav_child_indent": False, # Remove o recuo exagerado dos submenus
    "sidebar_nav_compact_style": True, # Deixa os itens mais próximos e densos
    
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default", 
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# ... final do arquivo ...
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# --- ADICIONE ESTAS DUAS LINHAS PARA OS UPLOADS ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')