# Generated by Django 6.0.7 on 2026-07-25 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('contato_principal', models.CharField(max_length=100)),
                ('franquia_horas', models.PositiveIntegerField(default=10, help_text='Total de horas mensais contratadas')),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ex: Suporte OLT Huawei, Consultoria BGP, etc.', max_length=100)),
                ('texto_base', models.TextField(help_text='Cole aqui o corpo do contrato')),
                ('status', models.CharField(choices=[('P', 'Pendente de Assinatura'), ('A', 'Assinado'), ('C', 'Cancelado')], default='P', max_length=1)),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='gestao.cliente')),
            ],
        ),
    ]
