# Generated by Django 6.0.7 on 2026-07-28 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='data_assinatura',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='ip_assinatura',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='texto_base',
        ),
        migrations.AddField(
            model_name='contrato',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Validade padrão de 1 ano', null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='franquia_horas',
            field=models.IntegerField(default=10, help_text='Total de horas mensais contratadas'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('RT1', 'Consultoria Nível 1 - Com RT'), ('RT2', 'Consultoria Nível 2 - Com RT'), ('RT3', 'Consultoria Nível 3 - Com RT'), ('SR1', 'Consultoria Nível 1 - Sem RT'), ('SR2', 'Consultoria Nível 2 - Sem RT'), ('SR3', 'Consultoria Nível 3 - Sem RT')], max_length=3),
        ),
        migrations.CreateModel(
            name='FinanceiroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, help_text='Ex: 1500.00', max_digits=10)),
                ('dia_vencimento', models.IntegerField(help_text='Dia do mês para vencimento (Ex: 10)')),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('BOL', 'Boleto Bancário'), ('TRA', 'Transferência (TED/DOC)')], default='PIX', max_length=3)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='gestao.cliente')),
            ],
            options={
                'verbose_name': 'Perfil Financeiro',
                'verbose_name_plural': 'Perfis Financeiros',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(help_text='Ex: Janeiro/2026', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pago'), ('A', 'Aberto / Pendente'), ('A', 'Atrasado')], default='A', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='gestao.cliente')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Histórico de Pagamentos',
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
