# Generated by Django 6.0.7 on 2026-07-28 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_remove_cliente_data_cadastro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Consultoria Nível 1 - Com RT', max_length=150)),
                ('texto_base', models.TextField(help_text='Use variáveis: {{ cliente.nome_fantasia }}, {{ cliente.cnpj }}, {{ financeiro.valor_mensalidade }}, etc.')),
            ],
            options={
                'verbose_name': 'Modelo de Contrato',
                'verbose_name_plural': 'Modelos de Contratos',
            },
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='arquivo_pdf',
            field=models.FileField(blank=True, help_text='Faça o upload do PDF após o cliente assinar.', null=True, upload_to='contratos/'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('P', 'Pago'), ('A', 'Aberto / Pendente'), ('T', 'Atrasado')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='contrato',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestao.modelocontrato'),
        ),
    ]
