# Generated by Django 6.0.7 on 2026-07-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_modelocontrato_remove_contrato_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do representante', max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço completo da sede', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, help_text='Ex: casado(a), solteiro(a)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(blank=True, default='brasileiro(a)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rg',
            field=models.CharField(blank=True, help_text='RG do representante', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato_principal',
            field=models.CharField(help_text='Nome do Diretor/Administrador', max_length=100),
        ),
    ]
